name: Docker Build and Push CI

on:
  push:
    branches:
      - "**"

permissions:
  id-token: write  # This is required for requesting the JWT
  contents: read   # This is required for actions/checkout

env:
  AWS_REGION: 'eu-west-1'
  ECR_REPOSITORY: 'datacentre_updater'
  AWS_ROLE: 'github-eu-west-1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Image Tag
        id: tag
        run: echo "TAG_NAME=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV
      - name: Print Image Tag
        run: echo "Tag Name for the Image ${{ env.TAG_NAME }}"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ROLE }}
          role-session-name: AWSSession
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'
      - name: Build the Docker image
        run: docker build -f docker/Dockerfile --tag ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-1.amazonaws.com/$ECR_REPOSITORY:$TAG_NAME .
      - name: Push the Docker image
        run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-1.amazonaws.com/$ECR_REPOSITORY:$TAG_NAME
